### PR TITLE
feat: use openapigen v7.0.0

### LINKED ISSUE #38: Update version of openapi-generator-cli in makefile, use python instead of python-nextgen
Apparently, in openapi-generator-cli, the python-nextgen matured and is now just "python". We should update our makefile to use newer docker image, and replace python-nextgen with python

### LINKED ISSUE #46: Running latest version doesn't work
Installing metal-python and running a simple import returns an error. The reason for this is that pydantic v2 is being pulled in and has backwards incompatible changes.

```
>>> import equinix_metal
/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/__init__.py", line 23, in <module>
    from equinix_metal.api.authentication_api import AuthenticationApi
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/api/__init__.py", line 6, in <module>
    from equinix_metal.api.authentication_api import AuthenticationApi
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/api/authentication_api.py", line 27, in <module>
    from equinix_metal.models.auth_token import AuthToken
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/models/__init__.py", line 53, in <module>
    from equinix_metal.models.create_device_request import CreateDeviceRequest
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/models/create_device_request.py", line 24, in <module>
    from equinix_metal.models.device_create_in_facility_input import DeviceCreateInFacilityInput
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/models/device_create_in_facility_input.py", line 25, in <module>
    from equinix_metal.models.facility_input_facility import FacilityInputFacility
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/models/facility_input_facility.py", line 29, in <module>
    class FacilityInputFacility(BaseModel):
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/equinix_metal/models/facility_input_facility.py", line 39, in FacilityInputFacility
    any_of_schemas: List[str] = Field(FACILITYINPUTFACILITY_ANY_OF_SCHEMAS, const=True)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smartinelli/src/myvenvvv/lib/python3.11/site-packages/pydantic/fields.py", line 757, in Field
    raise PydanticUserError('`const` is removed, use `Literal` instead', code='removed-kwargs')
pydantic.errors.PydanticUserError: `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.3/u/removed-kwargs
>>> 
```

### PR DESCRIPTION
**Pull request by t0mk**
This PR fixes openapigen docker image to tag v7.0.0.

It should fix pydantic to <2 and fix #46.
https://github.com/equinix-labs/metal-python/compare/openapigen_v7.0.0?expand=1#diff-f3eb11c13067f3b9839bc8411d47ce2d7d9c99c64478174609246bb88f41692cL4

also fixes #38

### CODE REVIEW

**Comment by ctreatma** [comment]
Are there new options we can set for the generator?  It looks like there are a lot of potentially unnecessary or undesirable changes here; the docs seem to have been deleted entirely, and a bunch of `*_api.py` files have either been moved or deleted as well.

**Comment by t0mk** [comment]
@ctreatma  Yes, the module seem to have changed :(. I need to check that `python` is indeed a sucessor of `python-nextgen` but if yes, it's not great that the generator changes module structure this much :(.

Docs moved:
https://github.com/equinix-labs/metal-python/blob/openapigen_v7.0.0/equinix_metal/docs/apis/tags/DevicesApi.md

There don't seem to be new params relevant to the changes:
https://openapi-generator.tech/docs/generators/python/
(unless they're uncdocumented)

I make this WIP

**Comment by t0mk** [comment]
@ctreatma, yesterday I accidentaly generated the code with the old-obsoleted `python` generator from the v6 openapigen, that's why the structure was so mangled.

The `python` generator is indeed sucessor of the experimental `python-nextgen`. I generated code with `python` generator from v7.0.0 now and the diff is leaner.

You can see Makefile updates in https://github.com/equinix-labs/metal-python/pull/47/commits/fe07e9b8d1754d1710713c0aed242955516c51c3 and the generated code update in https://github.com/equinix-labs/metal-python/pull/47/commits/0fc266ab395b94a30a7e39b4a437bb0a275ee242

Please review

**Review by ctreatma — APPROVED** [review]
This looks way better!  Thanks!

**Pull request merged**
