### PR TITLE
release process to RELEASE.md, makefile improvements

### PR DESCRIPTION
**Pull request by t0mk**
Add RELEASE.md

@displague please take a look

### CODE REVIEW

**Comment by t0mk** [comment]
relates to #3

**Comment by t0mk** [comment]
We can discuss the naming in here a bit more. This repo is `metal-python`, the package name is `equinix-metal`, and the python import will be `import equinix_metal`. I hope this is alright.

**Comment by ctreatma** [comment]
I'm on board with this as-is, but it would be nice to have a more automated release process to reduce the chance for mistakes.  At this point, I think our most-automated release process is in CPEM, which responds to git tags by creating a GitHub release with auto-generated release notes and publishing the release artifacts to the correct artifact repository: https://github.com/equinix/cloud-provider-equinix-metal/blob/main/.github/workflows/release.yaml

**Comment by t0mk** [comment]
This is not relevant anymore

**Pull request closed without merging**
