### PR TITLE
Fix API spec by removing enum from "line" arg of the Plan resource

### PR DESCRIPTION
**Pull request by t0mk**
When implementing hardware reservation in Ansible collection, I noticed the generated client was failing on "reserved" value in "line" argument of the Plan resource (linked from hardware reservation). It's originally limited to "baremetal". This PR fixes the spec so that it doesn't fail on "reserved", which is the case for reserved hardware.

This should be fixed in the API spec upstream.

### CODE REVIEW

**Comment by ctreatma** [comment]
We ran into the same issue on equinix-labs/metal-java#65; in that case we opted to remove the enum and make the `plan` a plain string.  My concern with the `line` enum is that there are additional values for `line` that aren't supposed to be returned by the API, but if that ever _did_ happen, SDKs that have strict validation for `line` would be broken because of the new, "invalid" values.

**Comment by t0mk** [comment]
@ctreatma I removed the enum

**Comment by ctreatma** [comment]
@t0mk I still see the previous changes in the file view for this PR.  Could you double-check that the branch is updated?

**Comment by t0mk** [comment]
@ctreatma Yes, sorry I didn't push. Thanks for letting me know. It's updated now, I checked the diff.

**Review by ctreatma — APPROVED** [review]
LGTM.  I'm attempting to upstream this patch; once that gets merged we can come back and clean up.

**Pull request merged**
